### ISSUE TITLE
Rename repository to "ruby-style-guide"

### ISSUE THREAD

**Issue by dzhlobo** [datarockets/ruby-style#235]
@roman-dubrovsky, I'd like to rename the repo not gem to "ruby-style-guide". It doesn't require a gem to be renamed but it would make it more descriptive on our https://github.com/datarockets page. Do you have any objections?

Right now we duplicate word "datarockets" twice: "datarockets/datarockets-style" and I think a new name would be nicer.

**Comment by roman-dubrovsky** [comment]
ok, but I still prefer to leave it `datarockets-style` : easier searching in the browser (when you start printing gem name) + `we duplicate word "datarockets" twice` only in datarockets repo but `ruby-style-guide` can be confused for guys who fork this project.

**Comment by DDKatch** [comment]
@roman-dubrovsky it is better to rename it, because a lot more people know about ruby and style guides not about datarockets style
<img width="1358" alt="Screen Shot 2021-01-19 at 12 00 24 AM" src="https://user-images.githubusercontent.com/14095146/104962494-95c68700-59e9-11eb-879b-936492eb852a.png">
It is easier to google for an average ruby developer (not only the datarocker), so it can become more popular much faster, which leads to more popularity of the company which means more money/people would like to share/join the stake.

**Comment by dzhlobo** [comment]
I've renamed the repo to "ruby-style" for now and highlighted it on https://github.com/datarockets.
